
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.system.admin }}
  namespace: {{ .Values.namespaces.system}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.system.admin }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.system.admin }}
  namespace: {{ .Values.namespaces.system}}

---


apiVersion: v1
kind: Secret
metadata:
  name: admin-token
  annotations:
    kubernetes.io/service-account.name: {{ .Values.system.admin }}
  namespace: {{ .Values.namespaces.system}}
type: kubernetes.io/service-account-token

---



apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespaces.system }}
  namespace: {{ .Values.namespaces.system }}
