apiVersion: v1
data:
  crt: >-
    {{ .Values.system.crt}}
  key: >-
    {{ .Values.system.key}}

kind: Secret
metadata:
  labels:
    app: dashpool
  name: dashpool-cfg
  namespace:  {{ .Values.namespaces.system}}
type: Opaque