apiVersion: v1
data:
  crt: >-
    {{ .Values.system.crt}}
  key: >-
    {{ .Values.system.key}}

kind: Secret
metadata:
  labels:
    app: dashpool
  name: dashpool-cfg
  namespace:  {{ .Values.namespaces.system}}
type: Opaque


---

{{ if .Values.system.docker }}

apiVersion: v1
data:
  .dockerconfigjson: >-
    {{ .Values.system.docker }}

kind: Secret
metadata:
  name: regcred
  namespace:  {{ .Values.namespaces.apps}}
type: kubernetes.io/dockerconfigjson

{{ end }}

