apiVersion: v1
data:
  crt: >-
    {{ .Values.system.crt}}
  key: >-
    {{ .Values.system.key}}
  kubernetes: >-
    {{ .Values.system.kubernetes }}

kind: Secret
metadata:
  labels:
    app: dashpool
  name: dashpool-cfg
  namespace:  {{ .Values.namespaces.system}}
type: Opaque


---

apiVersion: v1
data:
  .dockerconfigjson: >-
    {{ .Values.system.docker }}

kind: Secret
metadata:
  name: regcred
  namespace:  {{ .Values.namespaces.apps}}
type: Opaque

