{{ if .Values.components.example }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-server-deployment
  namespace: {{ .Values.namespaces.apps }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-server
  template:
    metadata:
      labels:
        app: mock-server
    spec:
      containers:
        - name: mock-server
          image: dashpool/exampleapp:latest
          imagePullPolicy: IfNotPresent    

---
apiVersion: v1
kind: Service
metadata:
  name: mock-server-service
  namespace: {{ .Values.namespaces.apps }}
spec:
  selector:
    app: mock-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mockserver-ingress
  namespace: {{ .Values.namespaces.apps }}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespaces.system }}-redirect-https@kubernetescrd,{{ .Values.namespaces.system }}-dash@kubernetescrd,{{ .Values.namespaces.system }}-strip-auth-cookie@kubernetescrd 
spec:
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mock-server-service
                port:
                  number: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mockserver-secure-ingress
  namespace: {{ .Values.namespaces.apps }}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: secure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespaces.system }}-auth@kubernetescrd,{{ .Values.namespaces.system }}-dash@kubernetescrd,{{ .Values.namespaces.system }}-strip-auth-cookie@kubernetescrd 
spec:
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mock-server-service
                port:
                  number: 5000


{{ end }}