
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespaces.system }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dashpool/frontend:{{ .Values.components.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 30m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /index.html
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        - name: SERVICE_WORKER_CACHE_NAME
          value: {{ .Values.components.version }}
        - name: MONGODB_URI
          value: {{ .Values.system.mongohost }}
        - name: MONGODB_DATABASE
          value: {{ .Values.system.dashpooldb }}
{{ if .Values.auth.skip }}          
        - name: SKIP_AUTH
          value: "true"
{{ end }}
      volumes:
      - name: config-volume
        configMap:
          name: frontend-configmap
          


---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespaces.system }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort



---



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespaces.system }}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespaces.system }}-redirect-https@kubernetescrd
spec:
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-secure-ingress
  namespace: {{ .Values.namespaces.system }}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: secure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespaces.system }}-auth-error@kubernetescrd,{{ .Values.namespaces.system }}-auth@kubernetescrd,{{ .Values.namespaces.system }}-dash@kubernetescrd 
spec:
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

---



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-secure-ingress-nopass
  namespace: {{ .Values.namespaces.system }}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: secure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespaces.system }}-strip-auth-cookie@kubernetescrd
spec:
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /index.html
            pathType: Exact
            backend:
              service:
                name: frontend
                port:
                  number: 80                  
          - path: /manifest.json
            pathType: Exact
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /_dash-component-suites
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80                  
          - path: /_dash-layout
            pathType: Exact
            backend:
              service:
                name: frontend
                port:
                  number: 80      
          - path: /_dash-dependencies
            pathType: Exact
            backend:
              service:
                name: frontend
                port:
                  number: 80          
          - path: /service-worker.js
            pathType: Exact
            backend:
              service:
                name: frontend
                port:
                  number: 80      

                                        
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-secure-ingress
  namespace: {{ .Values.namespaces.system }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: secure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespaces.system }}-auth@kubernetescrd,{{ .Values.namespaces.system }}-backend-strip@kubernetescrd 
spec:
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080


---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: backend-strip
  namespace: {{ .Values.namespaces.system }}  
spec:
  stripPrefix:
    prefixes:
      - /backend
