{{ if .Values.components.mongo }}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Values.namespaces.system }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.22
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Values.namespaces.system }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---

{{ end }}




---

{{ if .Values.components.mongoexpress }}



apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: {{ .Values.namespaces.system }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.2-20-alpine3.19
          resources:
            requests:
              cpu: 20m
              memory: 100Mi             
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://{{ .Values.system.mongohost }}
            - name: ME_CONFIG_SITE_BASEURL
              value: "/mongo"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: ""         
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: ""
          ports:
            - containerPort: 8081
---



apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: {{ .Values.namespaces.system }}
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  



{{ end }}