apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.apps }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.system }}


---


{{ if .Values.components.ingress }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.ingress }}  


{{ end }}