
apiVersion: batch/v1
kind: Job
metadata:
  name: dashpool-init
  namespace: {{ .Values.namespaces.system }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"  
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dashpool-init
          image: dashpool/admin:{{ .Values.components.version }}
          command: ["/bin/sh"]
          args: ["-c", "python3 /usr/src/app/cron.py"]
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/admin.cfg
              subPath: admin.cfg
          env:
          - name: DASHPOOL_VERSION
            value: "{{ .Values.components.version }}"
          - name: MONGODB_URI
            value: mongodb://{{ .Values.system.mongohost }}
          - name: MONGODB_DATABASE
            value: {{ .Values.system.dashpooldb }}                
      volumes:
      - name: config-volume
        configMap:
          name: admin-configmap
      - name: dashpool-cfg
        secret:
          secretName: dashpool-cfg  
      serviceAccountName: {{ .Values.system.admin }}

